# Generated by Django 5.2.6 on 2026-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_userprofile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='title',
            field=models.CharField(default='Internship Role', max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
    ]
