# Generated by Django 5.2.6 on 2026-02-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_internship_title_alter_internship_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='stipend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company_name',
            field=models.CharField(blank=True, default='Unknown Company', max_length=255, null=True),
        ),
    ]
