# Generated by Django 5.2.6 on 2026-02-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_internship_duration_internship_stipend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='application_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
