# Generated by Django 5.2.6 on 2026-03-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_savedinternship'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='work_type',
            field=models.CharField(choices=[('In-office', 'In-office'), ('Work from Home', 'Work from Home'), ('Field work', 'Field work'), ('Hybrid', 'Hybrid')], default='In-office', max_length=50),
        ),
    ]
